services:
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: otelcol-contrib
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55678:55678"
      - "55679:55679"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./config.yaml:/etc/otelcol-contrib/config.yaml
